### ISSUE TITLE
Support background images?

### ISSUE THREAD

**Issue by tmcw** [callmecavs/layzr.js#15]
We have [a very long page with big images as backgrounds](https://www.mapbox.com/about/team/) and would love to lazyload them, but they aren't image elements. Would it be possible to support background-url properties as well?

**Comment by callmecavs** [comment]
@tmcw shoutout DC! looking into this - it would require expanding the library to act on things other than images (see #14)

**Comment by callmecavs** [comment]
@tmcw this is live in the latest version, updated the docs to include details about the new bgAttr option: [http://callmecavs.github.io/layzr.js/](http://callmecavs.github.io/layzr.js/)

**Comment by callmecavs** [comment]
@tmcw did you end up using the lib? would love to start a showcase of how it's being used

**Comment by callmecavs** [comment]
@tmcw ping

**Comment by gplusdotgr** [comment]
@callmecavs I guess background images were removed from the script after all? can't find anything in the source or in the documentation

**Comment by callmecavs** [comment]
@gkatsanos the way they're applied is different in v2.  see #54, where I detail the process - basically instead of having separate attributes, use the events system to remove the `src` and apply the image as a background inline.

biggest problem with background images is `srcset` support.  [`image-set` support](http://caniuse.com/#search=image-set) is spotty, and most browsers don't support programmatically getting the image source that was chosen from the options in `srcset`, so intelligently loading background images becomes impossible unless I were to re-implement the logic that determines the source from the options in `srcset`/`sizes` within the lib
