### ISSUE TITLE
android tested?

### ISSUE THREAD

**Issue by renege** [callmecavs/layzr.js#17]
is it even tested on android? it doesnt work

**Comment by callmecavs** [comment]
yes, it is tested on android... got any device/browser info? anything more specific than "it doesn't work"?

the problem you're experiencing is likely caused by the way the scroll event fires on mobile chrome/safari. **the scroll event fires after the momentum scrolling has stopped, not while the user is scrolling** and so it's possible that the images will come into view "broken", and reveal after the momentum scrolling has stopped.

mobile safari 8 fixes the way the scroll event fires, so you'll only see this in versions 6 and 7. as far as i know, mobile chrome has yet to make this fix, meaning you're likely to see it on a whole lot of android devices. to my knowledge, there's no workaround for this currently - would love a resource detailing how to compensate for this if one exists/anyone has one.

**Comment by callmecavs** [comment]
ping @renege

**Comment by ImBobby** [comment]
I test the [documentation demo page](http://callmecavs.github.io/layzr.js/) using BrowserStack, this plugin worked on:
- Android browser 4.4+
- iOS6+
- IE mobile (Windows phone)

Took a quick look at [Can I Use for rAF support](http://caniuse.com/#feat=requestanimationframe) and it only supported on Android 4.4+ and iOS7. iOS6 support rAF with `webkit` prefix. If you can add rAF polyfill to your documentation page, I am sure it will have better mobile browser support.

Adding those 3 browsers to browser support section in the documentation might be a good idea.

**Comment by callmecavs** [comment]
@ImBobby thanks for running that dude, you rock! :metal:

I'm aware of the rAF support, couple of my thoughts on it below:
- not as concerned about Android Browser as I am about Chrome for Android - based on Can I Use's usage statistics, Android Browser's usage accounts for < 2.5% globally, whereas Chrome for Android accounts for almost 11%
- global usage for all Mobile Safari versions less than 6 is < .05%, imo not really worth worrying about

regardless, i'll definitely update the browser support section to include a link to Paul Irish's [rAF polyfill](https://gist.github.com/paulirish/1579671). preciate your thoughts on the matter
