### ISSUE TITLE
ajax issues

### ISSUE THREAD

**Issue by magicspon** [callmecavs/layzr.js#63]
Hello,

I'm using your plugin along with smoothstate.js.  Smoothstate uses ajax to transition between pages.  It also caches a number of pages.  Anyhow... 

The first time I navigate to a page, the images are loaded via layzr as expected, "lovely stuff".  However, the second time the page is visited, the images already have there src attributes and therefore no data- attributes.  So layzr replaces the src with null.. eeee!

Any thoughts on this.  I kind of only want to run the plugin if the images don't already have a source.  

I'm using the plugin via NPM.  

Thanks

**Comment by callmecavs** [comment]
@magicspon Layzr only acts on elements that have the [`normal` attribute](https://github.com/callmecavs/layzr.js#data-normal), so the problem can't be the existing `src` attribute. perhaps its an empty `data-normal` attribute, causing the `src` to be re-set to null?

I'm going to close this issue, as it seems like this issue is particular to your environment, and perhaps other libraries you're using - not Layzr itself. happy to provide more support if I can, just need more details and preferably a demo of some sort
