### ISSUE TITLE
update nodes before check on events

### ISSUE THREAD

**Issue by krzysiek1507** [callmecavs/layzr.js#75]
Hi, shouldn't be [here](https://github.com/callmecavs/layzr.js/blob/master/src/layzr.js#L56) `update()` before `check()`? Sometime it tries to set `src` twice.

**Comment by callmecavs** [comment]
I dont think so, because unless an image has been loaded, the elements to check should be the same. if we introduce a call to `update` where you describe, we'll be repeatedly updating the list of elements for no reason (and taking a performance hit for using `document.querySelectorAll` on every tick of the scroll event).

for that reason, we call `update` [here](https://github.com/callmecavs/layzr.js/blob/master/src/layzr.js#L98) in the `setSource` function, only after an image source has been set.
