### ISSUE TITLE
DOMContentLoaded not firing when used in requirejs

### ISSUE THREAD

**Issue by bmsterling** [callmecavs/layzr.js#8]
`document.addEventListener('DOMContentLoaded', this._create.bind(this), false);` does not fire off when layzr is used with requirejs.  Checking for `readyState` is `complete` seems to fix this:

```
    if (document.readyState === "complete") {
      this._create();
    } else {
      // call to create
      document.addEventListener('DOMContentLoaded', this._create.bind(this), false);
    }
```

**Comment by callmecavs** [comment]
DOMContentLoaded is _not_ actually needed on the client side, can confirm its working in all supported browsers.  assuming it's because getElementsByTag returns a live nodelist, which is updating itself as the DOM fills with images (hopefully).

replace, line 33:

``` javascript
document.addEventListener('DOMContentLoaded', this._create.bind(this), false);
```

with:

``` javascript
this._create();
```

and kindly let me know if it works with RequireJS :pray:

if so i'll commit it as a fix for this issue.

**Comment by bmsterling** [comment]
This does work.

**Comment by callmecavs** [comment]
awesome! patch coming momentarily. thanks for the help!

**Comment by callmecavs** [comment]
pushed the patch to NPM as well

**Comment by fshowalter** [comment]
I think @bmsterling's initial suggestion might be the better way to go. I'm loading background images on elements that use pseudo elements with padding to ensure the element's dimensions maintain a given ratio. I'm running into a problem where `_create` is getting called while `document.readyState === "loading"` and while the nodes are present, the css hasn't been processed yet. Without the css, the pseudo elements aren't there, which causes the nodes to return an `offsetHeight` of `0` which causes layzr to think some of them aren't in the viewport.

**Comment by callmecavs** [comment]
@fshowalter what if, rather than waiting for DOMContentLoaded, which fires when the DOM state is 'interactive', we wait for the DOM readyState to be 'complete'?  take a look here: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

the check would look something like this instead (this would replace the call to _create on line 35):

``` javascript
document.onreadystatechange = function() {
  if(document.readyState === "complete") {
    this._create();
  }
}
```

i don't understand why the if/else statement by @bmsterling above works. if the script is loading so fast that it requires a docReady check, it doesn't make sense that checking the docReady state, without binding _create() to some kind of docReady event that fires when its 'complete', would make it work

**Comment by fshowalter** [comment]
@callmecavs Yes, there could be a race condition where it's not complete when you check, but is complete before the event handler is wired. So you'd need something like this:

```
document.onreadystatechange = function() {
  if(document.readyState == "complete") {
    this._create();
  }
}

this._create();
```

That still leaves the problem of the double call to `_create`. If you take out the second call, `_create` may never be called if `document.readyState` was already at `complete` when the script executed. Given that this is only a problem for background images, maybe only wire the event handler if there are any background images to lazy load? That doesn't fix the double call, but it does limit it somewhat. I'm sure there's a better way that I'm not seeing.

**Comment by callmecavs** [comment]
@fshowalter did a lot of thinking about this - the solution here might be to create the Layzr instance inside of some check to see if the document is ready, rather than have Layzr check internally if the DOM is ready. for example:

``` javascript
document.addEventListener('DOMContentLoaded', function() {
  // init Layzr once the DOM is ready, so it doesn't need to check
  var layzr = new Layzr();
});
```

this way, there's no race condition (and no duplication), and people can check if the DOM is ready in whatever way works best with their specific implementation - this may be the DOMContentLoaded event, the readyState if working with requireJS, etc.

would appreciate your thoughts/feedback on this. if we go this route, i'll be sure to make a note of it in the 'Create an Instance' section of the docs as well

**Comment by fshowalter** [comment]
@callmecavs, it's not a `DOMContentLoaded` issue. The nodes are all there. It's a CSS issue, and DOMContentLoaded doesn't guarantee that the CSS has been processed.  

Binding to the `onreadystatechange` would work, _but_ it'll also delay loading of all images until the event fires (which could be a while depending on what's on the page). It's not a bad way to go, but I've been thinking too, and I think the optimum solution would be to make `_create` idempotent. This way it could fire as soon as possible, updating all the nodes it can, then, possibly, fire again after the `onreadystatechange` event to catch any stragglers. 

The gotcha right now is that doing so would wire the `scroll` and `resize` handlers twice. Calling `_destroy` on the first line of `_create` would resolve this, but you'll have to be careful if you add anything extra to `_destroy`. Of course, at that point you could just create an `_unbindListeners` function.

**Comment by fshowalter** [comment]
@callmecavs Did a little more research. Take a look at how picturefill deals with it:

https://github.com/scottjehl/picturefill/blob/master/src/picturefill.js

Their create is idempotent, and they fire it first, then poll until the document readystate is complete, after which they fire again. Pretty bulletproof.

**Comment by callmecavs** [comment]
v2 will not include any DOM event hooks. it will be up to the user to call it at the time appropriate for their use case. this makes the most sense imo, given the variability in user environments and tooling
